linters-settings:
  errcheck:
    ignore: fmt:.*,github.com/go-kit/log:.*,github.com/go-kit/kit/log:.*,database/sql:Rollback,github.com/UNO-SOFT/ulog:.*

linters:
  enable:
    - dupl
    - goconst
    - misspell
    - unparam
    - prealloc
    - unused
    - staticcheck
    - gofmt
    - errorlint
    - noctx
    - sqlclosecheck
    - unconvert

  disable:
    - interfacer

issues:
  exclude:
    - "`?encodeFixed(32|64)Pb`? is unused"

# vim: set et shiftwidth=2:
